server:
  port: 8081
spring:
  application:
    name: manager_app
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: '0302'
    url: jdbc:mysql://localhost:3306/manager
    username: root
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true
