#profiles: test
#datasource:
#  username: root
#  password: root123
#  url: jdbc:mysql://localhost:3306/manager
#  driver-class-name: com.mysql.cj.jdbc.Driver
#bezkoder:
#  app:
#    jwtCookieName: bezkoder
#    jwtSecret: "======================BezKoder=Spring==========================="
#    jwtExpirationMs: 86400000
#    jwtExpirationRefresh: 604800000
